# Generated by Django 5.2 on 2025-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
